"""add language to posts

Revision ID: 6374a4a64fc6
Revises: c3e2f7fdbbfb
Create Date: 2020-03-11 14:09:27.358093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6374a4a64fc6'
down_revision = 'c3e2f7fdbbfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
